publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
backend:
  name: github
  repo: lipukule/site
  open_authoring: true
# backend:
  # name: git-gateway
  # branch: main
  # identity_url: "https://auth.lipukule.org/identity"
  # gateway_url:  "https://auth.lipukule.org/git"
  # site_domain:  "https://lipukule.org/"
collections:
  - name: "sitelen" # Used in routes, e.g., /admin/collections/blog
    label: "sitelen" # Used in the UI
    folder: "content/tok/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "nimi"
        name: "title"
        widget: "string"
      - label: "tenpo open"
        name: "date"
        widget: "datetime"
      - label: "poki"
        name: "poki"
        widget: "list"
      - label: "lipu li tan jan/kulupu/ante seme?"
        name: "janpali"
        widget: "list"
      - label: "sitelen kule"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "kule"
        name: "kule"
        widget: "select"
        options:
          - toki
          - ilo
          - sona
          - moku
          - musi
          - lon
          - ante
      - label: "sitelen"
        name: "body"
        widget: "markdown"
